/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 encenario.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/encenario.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.wctrophy_body_low_body_0.geometry} material={materials.body} position={[0, 0, 2.21]} rotation={[0, 0, -2.08]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.wctrophy_globe_low_globe_0.geometry} material={materials.globe} position={[0, 0, 2.21]} rotation={[0, 0, -2.08]} />
          </group>
        </group>
      </group>
      <group position={[-0.95, 5.11, -4.23]} rotation={[-Math.PI / 2, 0, 0]} scale={0.03}>
        <group position={[24.76, -5.53, 29.61]} rotation={[Math.PI / 2, 0, 0]} scale={3.46}>
          <mesh geometry={nodes.Mesh_0002.geometry} material={materials.Color_D01} />
          <mesh geometry={nodes.Mesh_0002_1.geometry} material={materials['Color_D01.001']} />
          <mesh geometry={nodes.Mesh_0002_2.geometry} material={materials['Color_D01.002']} />
          <mesh geometry={nodes.Mesh_0002_3.geometry} material={materials['Color_D01.003']} />
          <mesh geometry={nodes.Mesh_0002_4.geometry} material={materials['Color_D01.004']} />
          <mesh geometry={nodes.Mesh_0002_5.geometry} material={materials['Color_D01.005']} />
          <mesh geometry={nodes.Mesh_0002_6.geometry} material={materials['Color_D01.006']} />
          <mesh geometry={nodes.Mesh_0002_7.geometry} material={materials['Color_D01.007']} />
          <mesh geometry={nodes.Mesh_0002_8.geometry} material={materials['Color_D01.008']} />
          <mesh geometry={nodes.Mesh_0002_9.geometry} material={materials['Color_D01.009']} />
          <mesh geometry={nodes.Mesh_0002_10.geometry} material={materials['Color_D01.010']} />
          <mesh geometry={nodes.Mesh_0002_11.geometry} material={materials['Color_D01.011']} />
        </group>
      </group>
      <group position={[4.52, 10.36, -7.97]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, -9.69, 6.87]} rotation={[0, 1.57, 0]} scale={[146.69, 300.11, 128.21]}>
            <mesh geometry={nodes.Plane_plastic_white_0.geometry} material={materials.plastic_white} position={[0.89, 0, 0]} />
          </group>
        </group>
      </group>
      <group rotation={[-1.73, -0.07, 0.07]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['plastic_white.002']} position={[-25.82, 13.55, 16.95]} rotation={[0.19, 0.04, 1.46]} />
      </group>
      <group position={[1.11, 12.5, -12.67]} rotation={[-Math.PI / 2, 0, 0]} scale={0.03}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_6.geometry} material={materials.Football} position={[-24.84, 0, 0]} scale={10} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.Football} scale={10} />
        </group>
      </group>
      <group position={[9.37, 7.22, 1.61]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[2.02, 270.22, 0.16]} rotation={[1.58, 0.05, 0.01]} scale={-4.09}>
            <group position={[23.54, 98.5, -69.39]} rotation={[-0.01, 0, 0.1]}>
              <mesh geometry={nodes['Footballer010_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
              <mesh geometry={nodes['Footballer010_03_-_Defaultd_0'].geometry} material={materials['03_-_Defaultd']} />
              <mesh geometry={nodes['Footballer010_03_-_Defaultdf_0'].geometry} material={materials['03_-_Defaultdf']} />
              <mesh geometry={nodes['Footballer010_03_-_Defausdltd_0'].geometry} material={materials['03_-_Defausdltd']} />
              <mesh geometry={nodes['Footballer010_03_-_Defausdltdxc_0'].geometry} material={materials['03_-_Defausdltdxc']} />
              <mesh geometry={nodes['Footballer010_Material_#432_0'].geometry} material={materials.Material_432} />
              <mesh geometry={nodes['Footballer010_Material_#432z_0'].geometry} material={materials.Material_432z} />
              <mesh geometry={nodes.Footballer010_Wall_Paint_0.geometry} material={materials.Wall_Paint} />
            </group>
          </group>
        </group>
      </group>
      <group position={[-1.38, 4.67, -4.36]} rotation={[-Math.PI / 2, 0, 0]} scale={0.03}>
        <group position={[-120.96, -10.38, 43.11]} rotation={[Math.PI / 2, 0, 0]} scale={3.46}>
          <mesh geometry={nodes.Mesh_0003.geometry} material={materials['Color_D01.012']} />
          <mesh geometry={nodes.Mesh_0003_1.geometry} material={materials['Color_D01.013']} />
          <mesh geometry={nodes.Mesh_0003_2.geometry} material={materials['Color_D01.014']} />
          <mesh geometry={nodes.Mesh_0003_3.geometry} material={materials['Color_D01.015']} />
          <mesh geometry={nodes.Mesh_0003_4.geometry} material={materials['Color_D01.016']} />
          <mesh geometry={nodes.Mesh_0003_5.geometry} material={materials['Color_D01.017']} />
          <mesh geometry={nodes.Mesh_0003_6.geometry} material={materials['Color_D01.018']} />
          <mesh geometry={nodes.Mesh_0003_7.geometry} material={materials['Color_D01.019']} />
          <mesh geometry={nodes.Mesh_0003_8.geometry} material={materials['Color_D01.020']} />
          <mesh geometry={nodes.Mesh_0003_9.geometry} material={materials['Color_D01.021']} />
          <mesh geometry={nodes.Mesh_0003_10.geometry} material={materials['Color_D01.022']} />
          <mesh geometry={nodes.Mesh_0003_11.geometry} material={materials['Color_D01.023']} />
        </group>
      </group>
      <group position={[-0.47, 4.69, -4.24]} rotation={[-Math.PI / 2, 0, 0]} scale={0.03}>
        <group position={[159.74, 3.34, 47.3]} rotation={[Math.PI / 2, 0, 0]} scale={3.46}>
          <mesh geometry={nodes.Mesh_0004.geometry} material={materials['Color_D01.024']} />
          <mesh geometry={nodes.Mesh_0004_1.geometry} material={materials['Color_D01.025']} />
          <mesh geometry={nodes.Mesh_0004_2.geometry} material={materials['Color_D01.026']} />
          <mesh geometry={nodes.Mesh_0004_3.geometry} material={materials['Color_D01.027']} />
          <mesh geometry={nodes.Mesh_0004_4.geometry} material={materials['Color_D01.028']} />
          <mesh geometry={nodes.Mesh_0004_5.geometry} material={materials['Color_D01.029']} />
          <mesh geometry={nodes.Mesh_0004_6.geometry} material={materials['Color_D01.030']} />
          <mesh geometry={nodes.Mesh_0004_7.geometry} material={materials['Color_D01.031']} />
          <mesh geometry={nodes.Mesh_0004_8.geometry} material={materials['Color_D01.032']} />
          <mesh geometry={nodes.Mesh_0004_9.geometry} material={materials['Color_D01.033']} />
          <mesh geometry={nodes.Mesh_0004_10.geometry} material={materials['Color_D01.034']} />
          <mesh geometry={nodes.Mesh_0004_11.geometry} material={materials['Color_D01.035']} />
        </group>
      </group>
      <group position={[2.22, 10.39, -12.85]} rotation={[-Math.PI / 2, 0, 0]} scale={3.65}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0.66, -0.62, 0.12]} scale={1.24}>
            <mesh geometry={nodes.pCylinder3_lambert1_0.geometry} material={materials['lambert1.001']} position={[0, 0.73, 0]} />
          </group>
        </group>
      </group>
      <group position={[0.73, 10.57, -12.76]} rotation={[-Math.PI / 2, 0, 0]} scale={2.67}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.pCylinder1_lambert1_0.geometry} material={materials['lambert1.002']} position={[0, 3.25, 0.53]} scale={[7.11, 14.22, 7.11]} />
        </group>
      </group>
      <mesh geometry={nodes.Object_2001.geometry} material={materials['Scene_-_Root']} position={[2.57, -0.41, 3.32]} rotation={[-Math.PI / 2, 0, 0.9]} scale={4.92} />
      <group position={[-0.5, 7.17, -8.33]} rotation={[-Math.PI / 2, 0, 0]} scale={0.21}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.ground_herbe_2_Room_Entity_Material} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.pack_002_babyfoot___02___default} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.pack_002_babyfoot___material__1} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.pack_002_babyfoot___material__3} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.pack_002_babyfoot___material__4} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.pack_002_babyfoot___material__5} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.pack_002_babyfoot___material__6} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.pack_002_babyfoot___material__7} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.pack_002_babyfoot___material__8} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.pack_002_babyfoot___material__9} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.blanc_001_Room_Entity_Material} />
      </group>
      <group position={[3.91, 9.68, -9.56]} rotation={[0, 1.32, 0]} scale={0.23}>
        <group position={[0, 0.2, -0.1]}>
          <mesh geometry={nodes.Mesh_body.geometry} material={materials.plastic} />
          <mesh geometry={nodes.Mesh_body_1.geometry} material={materials.paintBlue} />
          <mesh geometry={nodes.Mesh_body_2.geometry} material={materials.lightFront} />
          <mesh geometry={nodes.Mesh_body_3.geometry} material={materials._defaultMat} />
          <mesh geometry={nodes.Mesh_body_4.geometry} material={materials.lightBack} />
          <mesh geometry={nodes.Mesh_body_5.geometry} material={materials.window} />
        </group>
        <group position={[-0.35, 0.3, 0.76]} rotation={[-Math.PI, 0, 0]} scale={-1}>
          <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={materials.carTire} />
          <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={materials._defaultMat} />
        </group>
        <group position={[0.35, 0.3, 0.76]}>
          <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={materials.carTire} />
          <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={materials._defaultMat} />
        </group>
        <group position={[-0.35, 0.3, -0.76]} rotation={[-Math.PI, 0, 0]} scale={-1}>
          <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={materials.carTire} />
          <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={materials._defaultMat} />
        </group>
        <group position={[0.35, 0.3, -0.76]}>
          <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={materials.carTire} />
          <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={materials._defaultMat} />
        </group>
      </group>
      <group position={[3.77, 8.38, -8.96]}>
        <group position={[0.15, 0.11, 0]} scale={0.76}>
          <mesh geometry={nodes.Mesh_barrel.geometry} material={materials.greyLight} />
          <mesh geometry={nodes.Mesh_barrel_1.geometry} material={materials.brownDark} />
          <mesh geometry={nodes.Mesh_barrel_2.geometry} material={materials.brown} />
        </group>
      </group>
      <group position={[-3.08, 8.38, -10.42]} rotation={[0, Math.PI / 6, 0]} scale={0.49}>
        <primitive object={nodes.Bone} />
        <primitive object={nodes.Bone037} />
        <primitive object={nodes.Bone014} />
        <primitive object={nodes.Bone035} />
        <primitive object={nodes.Bone036} />
        <primitive object={nodes.Bone038} />
        <skinnedMesh geometry={nodes.Cube001.geometry} material={materials['Material.026']} skeleton={nodes.Cube001.skeleton} />
        <skinnedMesh geometry={nodes.Cube001_1.geometry} material={materials['Material.027']} skeleton={nodes.Cube001_1.skeleton} />
      </group>
      <group position={[3.87, 9.68, -10.25]} rotation={[-Math.PI, 1.3, -Math.PI]} scale={0.23}>
        <group position={[0, 0.2, -0.1]}>
          <mesh geometry={nodes.Mesh_body001.geometry} material={materials['plastic.001']} />
          <mesh geometry={nodes.Mesh_body001_1.geometry} material={materials['paintBlue.001']} />
          <mesh geometry={nodes.Mesh_body001_2.geometry} material={materials['lightFront.001']} />
          <mesh geometry={nodes.Mesh_body001_3.geometry} material={materials['_defaultMat.001']} />
          <mesh geometry={nodes.Mesh_body001_4.geometry} material={materials['lightBack.001']} />
          <mesh geometry={nodes.Mesh_body001_5.geometry} material={materials['window.001']} />
        </group>
        <group position={[-0.35, 0.3, 0.76]} rotation={[-Math.PI, 0, 0]} scale={-1}>
          <mesh geometry={nodes.Mesh_wheel_frontLeft001.geometry} material={materials['carTire.001']} />
          <mesh geometry={nodes.Mesh_wheel_frontLeft001_1.geometry} material={materials['_defaultMat.001']} />
        </group>
        <group position={[0.35, 0.3, 0.76]}>
          <mesh geometry={nodes.Mesh_wheel_frontLeft001.geometry} material={materials['carTire.001']} />
          <mesh geometry={nodes.Mesh_wheel_frontLeft001_1.geometry} material={materials['_defaultMat.001']} />
        </group>
        <group position={[-0.35, 0.3, -0.76]} rotation={[-Math.PI, 0, 0]} scale={-1}>
          <mesh geometry={nodes.Mesh_wheel_frontLeft001.geometry} material={materials['carTire.001']} />
          <mesh geometry={nodes.Mesh_wheel_frontLeft001_1.geometry} material={materials['_defaultMat.001']} />
        </group>
        <group position={[0.35, 0.3, -0.76]}>
          <mesh geometry={nodes.Mesh_wheel_frontLeft001.geometry} material={materials['carTire.001']} />
          <mesh geometry={nodes.Mesh_wheel_frontLeft001_1.geometry} material={materials['_defaultMat.001']} />
        </group>
      </group>
      <mesh geometry={nodes.Object001_Object001_mtl_0.geometry} material={materials.Object001_mtl} position={[-4.09, 6.81, -11.74]} rotation={[-1.66, 0.07, -0.49]} scale={0.06} />
      <group scale={4.48}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.010']} />
      </group>
      <group position={[0, 7.18, -8.95]} scale={4.48}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Plane002_4.geometry} material={materials['Material.008']} />
      </group>
      <group position={[9.01, 7.13, 0]} scale={4.48}>
        <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Plane003_3.geometry} material={materials['Material.033']} />
      </group>
      <mesh geometry={nodes['image-removebg-preview'].geometry} material={materials['image-removebg-preview']} position={[4.4, 3.51, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={6.56} />
      <group position={[-0.57, 10.52, -13.06]} rotation={[2.72, -0.01, -3.14]} scale={0.19}>
        <mesh geometry={nodes.Circle038.geometry} material={materials['FrameGrey.001']} />
        <mesh geometry={nodes.Circle038_1.geometry} material={materials['Front.001']} />
        <mesh geometry={nodes.Circle038_2.geometry} material={materials['Antennaline.001']} />
        <mesh geometry={nodes.Circle038_3.geometry} material={materials['BackGrey.001']} />
        <mesh geometry={nodes.Circle038_4.geometry} material={materials['Rubber.001']} />
        <mesh geometry={nodes.AntennaLineBottom001.geometry} material={materials['Antennaline.001']} position={[0, -2.68, 0]} />
        <mesh geometry={nodes.AntennaLineTop001.geometry} material={materials['Antennaline.001']} position={[0, 0.02, 0]} />
        <mesh geometry={nodes.AppleLogo001.geometry} material={materials['AppleLogo.001']} position={[0.17, 0.52, -0.08]} />
        <mesh geometry={nodes.BackCameraBottomGreyRing001.geometry} material={materials['BackCaneraGrayRIng.002']} position={[0.7, 0.88, -0.09]} />
        <mesh geometry={nodes.BackCameraBottomLens001.geometry} material={materials['Lens.001']} position={[0.7, 0.88, -0.08]} />
        <mesh geometry={nodes.BackCameraP1001.geometry} material={materials['Black.015']} position={[0.7, 1.03, -0.09]} />
        <mesh geometry={nodes.BackCameraTopGreyRing001.geometry} material={materials['BackCaneraGrayRIng.002']} position={[0.7, 1.18, -0.09]} />
        <mesh geometry={nodes.BackCameraTopLens001.geometry} material={materials['Lens.001']} position={[0.7, 1.18, -0.08]} />
        <mesh geometry={nodes.CameraBump001.geometry} material={materials['Frame.001']} position={[0.7, 1.04, -0.08]} />
        <mesh geometry={nodes.FlashBG001.geometry} material={materials['PinkFlash.002']} position={[0.71, 1.03, -0.09]} />
        <mesh geometry={nodes.FrontCameraContainer001.geometry} material={materials['FrontCameraBlack.002']} position={[0.34, 1.32, 0.08]} />
        <mesh geometry={nodes.FrontSpeakerBG001.geometry} material={materials['FrontSpeaker.001']} position={[0.16, 1.32, 0.08]} />
        <mesh geometry={nodes.iPhoneLogo001.geometry} material={materials['iPhoneLogo.001']} position={[0.2, -1.18, -0.08]} />
        <mesh geometry={nodes.MuteSwitch001.geometry} material={materials['FrameGrey.001']} position={[-0.65, 0.92, 0.01]} />
        <group position={[0.97, 0.56, 0]}>
          <mesh geometry={nodes.Circle032.geometry} material={materials['FrameGrey.001']} />
          <mesh geometry={nodes.Circle032_1.geometry} material={materials['Frame.001']} />
        </group>
        <group position={[0.98, -0.04, 0]}>
          <mesh geometry={nodes.Circle031.geometry} material={materials['Black.014']} />
          <mesh geometry={nodes.Circle031_1.geometry} material={materials['FrameGrey.001']} />
        </group>
        <mesh geometry={nodes.SCREEN.geometry} material={materials['Display.002']} />
        <mesh geometry={nodes.VolumeButtons001.geometry} material={materials['FrameGrey.001']} position={[-0.66, 0.21, 0]} />
      </group>
      <group position={[3.86, 8.01, -7.26]} rotation={[-0.2, -0.27, -0.03]} scale={2.77}>
        <mesh geometry={nodes.Generic_Les_Paul_Mesh.geometry} material={materials.Plastic} />
        <mesh geometry={nodes.Generic_Les_Paul_Mesh_1.geometry} material={materials['Golden Metal']} />
        <mesh geometry={nodes.Generic_Les_Paul_Mesh_2.geometry} material={materials['Fretboard Wood']} />
        <mesh geometry={nodes.Generic_Les_Paul_Mesh_3.geometry} material={materials.Ivory} />
        <mesh geometry={nodes.Generic_Les_Paul_Mesh_4.geometry} material={materials.Finish} />
        <mesh geometry={nodes.Generic_Les_Paul_Mesh_5.geometry} material={materials['Silver Metal']} />
        <mesh geometry={nodes.Generic_Les_Paul_Mesh_6.geometry} material={materials.Knobs} />
        <mesh geometry={nodes.Generic_Les_Paul_Mesh_7.geometry} material={materials['Pickup Wrap Fabric']} />
      </group>
      <mesh geometry={nodes.plant001.geometry} material={materials['Material.028']} position={[3.93, 12.3, -8.04]} scale={0.44}>
        <mesh geometry={nodes.Circle001.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.NurbsPath006.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.NurbsPath007.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.NurbsPath008.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.NurbsPath009.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.NurbsPath010.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.NurbsPath011.geometry} material={materials['Material.017']} />
      </mesh>
      <group position={[3.82, 10.9, -8.73]} scale={0.16}>
        <mesh geometry={nodes.ship_wreck_8angles_1.geometry} material={materials['wood.020']} />
        <mesh geometry={nodes.ship_wreck_8angles_2.geometry} material={materials['iron.010']} />
        <mesh geometry={nodes.ship_wreck_8angles_3.geometry} material={materials['woodDark.002']} />
        <mesh geometry={nodes.ship_wreck_8angles_4.geometry} material={materials['window.002']} />
        <mesh geometry={nodes.ship_wreck_8angles_5.geometry} material={materials['leaves.006']} />
        <mesh geometry={nodes.ship_wreck_8angles_6.geometry} material={materials['_defaultMat.004']} />
      </group>
      <group position={[0, 0.55, 0]}>
        <mesh geometry={nodes.Circle_1.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Circle_2.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.Circle_3.geometry} material={materials['Material.032']} />
      </group>
      <group position={[3.68, 12.35, -10.47]} rotation={[0.77, 0, 0]}>
        <mesh geometry={nodes.Cube019.geometry} material={materials.StoneDark} />
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['White.029']} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials['Metal.076']} />
      </group>
      <mesh geometry={nodes.plant002.geometry} material={materials['Material.018']} position={[-2.46, 12.43, -12.83]} scale={0.44}>
        <mesh geometry={nodes.Circle002.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.NurbsPath001.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.NurbsPath002.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.NurbsPath003.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.NurbsPath004.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.NurbsPath005.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.NurbsPath012.geometry} material={materials['Material.024']} />
      </mesh>
      <group position={[4.33, 12.23, -9.94]} rotation={[3.06, -0.13, 3.13]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['StoneDark.001']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['White.001']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Metal.001']} />
      </group>
      <group position={[3.83, 12.23, -9.12]} rotation={[2.99, -1.02, 3.01]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials['StoneDark.002']} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['White.002']} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials['Metal.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/encenario.gltf')
