/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 escenario.gltf
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function Escenario(section, props) {


  
  const { nodes, materials } = useGLTF('models/escenariov2/encenario2.glb')
 
  const [isHovered, setIsHovered] = useState(false);
  const scaleFactor = isHovered ? 0.007 : 0.003; // Aumentar la escala en un 10% cuando se hace hover
  const yFactor = isHovered ? -0.75 : 0; // Aumentar la escala en un 10% cuando se hace hover

  const handleHover = (hover) => {
    setIsHovered(hover);
  };

  return (
    <group {...props} position-y={3} scale={0.203} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[0,yFactor,0]} onPointerEnter={() => handleHover(true)} onPointerLeave={() => handleHover(false)} scale={scaleFactor}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.wctrophy_body_low_body_0.geometry}
              material={materials.body}
              position={[0, 0, 2.211]}
              rotation={[0, 0, -2.084]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.wctrophy_globe_low_globe_0.geometry}
              material={materials.globe}
              position={[0, 0, 2.211]}
              rotation={[0, 0, -2.084]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-0.947, 5.112, -4.228]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      >
        <group
          position={[24.756, -5.529, 29.611]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={7.461}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0002.geometry}
            material={materials.Color_D01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0002_1.geometry}
            material={materials["Color_D01.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0002_2.geometry}
            material={materials["Color_D01.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0002_3.geometry}
            material={materials["Color_D01.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0002_4.geometry}
            material={materials["Color_D01.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0002_5.geometry}
            material={materials["Color_D01.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0002_6.geometry}
            material={materials["Color_D01.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0002_7.geometry}
            material={materials["Color_D01.007"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0002_8.geometry}
            material={materials["Color_D01.008"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0002_9.geometry}
            material={materials["Color_D01.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0002_10.geometry}
            material={materials["Color_D01.010"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0002_11.geometry}
            material={materials["Color_D01.011"]}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object001_Object001_mtl_0.geometry}
        material={materials.Object001_mtl}
        position={[-4.089, 6.813, -11.739]}
        rotation={[-1.662, 0.067, -0.491]}
        scale={0.055}
      />
      <group position={[4.521, 10.36, -7.967]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[0, -9.693, 6.874]}
            rotation={[0, 1.571, 0]}
            scale={[146.695, 300.111, 128.209]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane_plastic_white_0.geometry}
              material={materials.plastic_white}
              position={[0.892, 0, 0]}
            />
          </group>
        </group>
      </group>
      <group rotation={[-1.731, -0.072, 0.065]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["plastic_white.002"]}
          position={[-25.821, 13.55, 16.952]}
          rotation={[0.189, 0.045, 1.464]}
        />
      </group>
      <group
        position={[1.109, 12.5, -12.669]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.033}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.Football}
            position={[-24.842, 0, 0]}
            scale={10}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.Football}
            scale={10}
          />
        </group>
      </group>
      <group
        position={[9.373, 7.216, 1.607]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.006}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0]}>
            <group
              position={[2.015, 270.219, 0.163]}
              rotation={[1.575, 0.049, 0.008]}
              scale={-4.088}
            >
              <group
                position={[23.54, 98.5, -69.386]}
                rotation={[-0.005, 0, 0.105]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes["Footballer010_03_-_Default_0"].geometry}
                  material={materials["03_-_Default"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes["Footballer010_03_-_Defaultd_0"].geometry}
                  material={materials["03_-_Defaultd"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes["Footballer010_03_-_Defaultdf_0"].geometry}
                  material={materials["03_-_Defaultdf"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes["Footballer010_03_-_Defausdltd_0"].geometry}
                  material={materials["03_-_Defausdltd"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes["Footballer010_03_-_Defausdltdxc_0"].geometry}
                  material={materials["03_-_Defausdltdxc"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes["Footballer010_Material_#432_0"].geometry}
                  material={materials.Material_432}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes["Footballer010_Material_#432z_0"].geometry}
                  material={materials.Material_432z}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Footballer010_Wall_Paint_0.geometry}
                  material={materials.Wall_Paint}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
      <group scale={4.483}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_2.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <group
        position={[-1.383, 4.666, -4.36]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      >
        <group
          position={[-120.961, -10.38, 43.106]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={3.461}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0003.geometry}
            material={materials["Color_D01.012"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0003_1.geometry}
            material={materials["Color_D01.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0003_2.geometry}
            material={materials["Color_D01.014"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0003_3.geometry}
            material={materials["Color_D01.015"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0003_4.geometry}
            material={materials["Color_D01.016"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0003_5.geometry}
            material={materials["Color_D01.017"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0003_6.geometry}
            material={materials["Color_D01.018"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0003_7.geometry}
            material={materials["Color_D01.019"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0003_8.geometry}
            material={materials["Color_D01.020"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0003_9.geometry}
            material={materials["Color_D01.021"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0003_10.geometry}
            material={materials["Color_D01.022"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0003_11.geometry}
            material={materials["Color_D01.023"]}
          />
        </group>
      </group>
      <group
        position={[-0.473, 4.693, -4.236]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      >
        <group
          position={[159.743, 3.341, 47.305]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={3.461}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0004.geometry}
            material={materials["Color_D01.024"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0004_1.geometry}
            material={materials["Color_D01.025"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0004_2.geometry}
            material={materials["Color_D01.026"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0004_3.geometry}
            material={materials["Color_D01.027"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0004_4.geometry}
            material={materials["Color_D01.028"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0004_5.geometry}
            material={materials["Color_D01.029"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0004_6.geometry}
            material={materials["Color_D01.030"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0004_7.geometry}
            material={materials["Color_D01.031"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0004_8.geometry}
            material={materials["Color_D01.032"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0004_9.geometry}
            material={materials["Color_D01.033"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0004_10.geometry}
            material={materials["Color_D01.034"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0004_11.geometry}
            material={materials["Color_D01.035"]}
          />
        </group>
      </group>
      <group position={[0, 7.181, -8.948]} scale={4.483}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_2.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_3.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_4.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <group position={[9.006, 7.13, 0]} scale={4.483}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_2.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_3.geometry}
          material={materials["Material.033"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["image-removebg-preview"].geometry}
        material={materials["image-removebg-preview"]}
        position={[4.399, 3.511, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={6.563}
      />
      <group
        position={[2.224, 10.389, -12.852]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.654}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0.662, -0.622, 0.119]} scale={1.241}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCylinder3_lambert1_0.geometry}
              material={materials["lambert1.001"]}
              position={[0, 0.728, 0]}
            />
          </group>
        </group>
      </group>
      <group
        position={[0.732, 10.568, -12.763]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.67}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1_lambert1_0.geometry}
            material={materials["lambert1.002"]}
            position={[0, 3.247, 0.535]}
            scale={[7.111, 14.222, 7.111]}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2001.geometry}
        material={materials["Scene_-_Root"]}
        position={[2.568, -0.411, 3.318]}
        rotation={[-Math.PI / 2, 0, 0.896]}
        scale={4.924}
      />
      <group
        position={[-0.503, 7.173, -8.005]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.205}
        
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.ground_herbe_2_Room_Entity_Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.pack_002_babyfoot___02___default}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials.pack_002_babyfoot___material__1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials.pack_002_babyfoot___material__3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.pack_002_babyfoot___material__4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials.pack_002_babyfoot___material__5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials.pack_002_babyfoot___material__6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials.pack_002_babyfoot___material__7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={materials.pack_002_babyfoot___material__8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials.pack_002_babyfoot___material__9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.blanc_001_Room_Entity_Material}
        />
      </group>
      <group
        position={[-0.568, 10.52, -13.064]}
        rotation={[2.724, -0.012, -3.137]}
        scale={0.192}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle038.geometry}
          material={materials["FrameGrey.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle038_1.geometry}
          material={materials["Front.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle038_2.geometry}
          material={materials["Antennaline.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle038_3.geometry}
          material={materials["BackGrey.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle038_4.geometry}
          material={materials["Rubber.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AntennaLineBottom001.geometry}
          material={materials["Antennaline.001"]}
          position={[0, -2.676, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AntennaLineTop001.geometry}
          material={materials["Antennaline.001"]}
          position={[0, 0.018, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AppleLogo001.geometry}
          material={materials["AppleLogo.001"]}
          position={[0.171, 0.521, -0.079]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BackCameraBottomGreyRing001.geometry}
          material={materials["BackCaneraGrayRIng.002"]}
          position={[0.702, 0.884, -0.094]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BackCameraBottomLens001.geometry}
          material={materials["Lens.001"]}
          position={[0.702, 0.884, -0.083]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BackCameraP1001.geometry}
          material={materials["Black.015"]}
          position={[0.705, 1.027, -0.095]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BackCameraTopGreyRing001.geometry}
          material={materials["BackCaneraGrayRIng.002"]}
          position={[0.702, 1.178, -0.094]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BackCameraTopLens001.geometry}
          material={materials["Lens.001"]}
          position={[0.702, 1.178, -0.083]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CameraBump001.geometry}
          material={materials["Frame.001"]}
          position={[0.704, 1.036, -0.079]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FlashBG001.geometry}
          material={materials["PinkFlash.002"]}
          position={[0.705, 1.027, -0.093]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FrontCameraContainer001.geometry}
          material={materials["FrontCameraBlack.002"]}
          position={[0.335, 1.323, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FrontSpeakerBG001.geometry}
          material={materials["FrontSpeaker.001"]}
          position={[0.156, 1.321, 0.077]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.iPhoneLogo001.geometry}
          material={materials["iPhoneLogo.001"]}
          position={[0.2, -1.175, -0.079]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MuteSwitch001.geometry}
          material={materials["FrameGrey.001"]}
          position={[-0.65, 0.92, 0.009]}
        />
        <group position={[0.97, 0.562, -0.004]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle032.geometry}
            material={materials["FrameGrey.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle032_1.geometry}
            material={materials["Frame.001"]}
          />
        </group>
        <group position={[0.978, -0.043, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle031.geometry}
            material={materials["Black.014"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle031_1.geometry}
            material={materials["FrameGrey.001"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SCREEN.geometry}
          material={materials["Display.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.VolumeButtons001.geometry}
          material={materials["FrameGrey.001"]}
          position={[-0.658, 0.208, -0.002]}
        />
      </group>
      <group
        position={[3.865, 8.009, -7.258]}
        rotation={[-0.199, -0.271, -0.028]}
        scale={2.765}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Generic_Les_Paul_Mesh.geometry}
          material={materials.Plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Generic_Les_Paul_Mesh_1.geometry}
          material={materials["Golden Metal"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Generic_Les_Paul_Mesh_2.geometry}
          material={materials["Fretboard Wood"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Generic_Les_Paul_Mesh_3.geometry}
          material={materials.Ivory}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Generic_Les_Paul_Mesh_4.geometry}
          material={materials.Finish}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Generic_Les_Paul_Mesh_5.geometry}
          material={materials["Silver Metal"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Generic_Les_Paul_Mesh_6.geometry}
          material={materials.Knobs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Generic_Les_Paul_Mesh_7.geometry}
          material={materials["Pickup Wrap Fabric"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant001.geometry}
        material={materials["Material.028"]}
        position={[3.93, 12.3, -8.042]}
        scale={0.443}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath006.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath007.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath008.geometry}
          material={materials["Material.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath009.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath010.geometry}
          material={materials["Material.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath011.geometry}
          material={materials["Material.017"]}
        />
      </mesh>
      <group position={[3.824, 10.9, -8.731]} scale={0.162}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_1.geometry}
          material={materials["wood.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_2.geometry}
          material={materials["iron.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_3.geometry}
          material={materials["woodDark.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_4.geometry}
          material={materials["window.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_5.geometry}
          material={materials["leaves.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ship_wreck_8angles_6.geometry}
          material={materials["_defaultMat.004"]}
        />
      </group>
      <group
        position={[3.909, 9.68, -9.562]}
        rotation={[0, 1.317, 0]}
        scale={0.226}
      >
        <group position={[0, 0.2, -0.1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_body.geometry}
            material={materials.plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_body_1.geometry}
            material={materials.paintBlue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_body_2.geometry}
            material={materials.lightFront}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_body_3.geometry}
            material={materials._defaultMat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_body_4.geometry}
            material={materials.lightBack}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_body_5.geometry}
            material={materials.window}
          />
        </group>
        <group
          position={[-0.35, 0.3, 0.76]}
          rotation={[-Math.PI, 0, 0]}
          scale={-1}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft.geometry}
            material={materials.carTire}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft_1.geometry}
            material={materials._defaultMat}
          />
        </group>
        <group position={[0.35, 0.3, 0.76]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft.geometry}
            material={materials.carTire}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft_1.geometry}
            material={materials._defaultMat}
          />
        </group>
        <group
          position={[-0.35, 0.3, -0.76]}
          rotation={[-Math.PI, 0, 0]}
          scale={-1}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft.geometry}
            material={materials.carTire}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft_1.geometry}
            material={materials._defaultMat}
          />
        </group>
        <group position={[0.35, 0.3, -0.76]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft.geometry}
            material={materials.carTire}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft_1.geometry}
            material={materials._defaultMat}
          />
        </group>
      </group>
      <group position={[3.775, 8.384, -8.956]}>
        <group position={[0.152, 0.106, 0]} scale={0.756}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_barrel.geometry}
            material={materials.greyLight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_barrel_1.geometry}
            material={materials.brownDark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_barrel_2.geometry}
            material={materials.brown}
          />
        </group>
      </group>
      <group
        position={[-3.077, 8.376, -10.417]}
        rotation={[0, Math.PI / 6, 0]}
        scale={0.489}
      >
        <primitive object={nodes.Bone} />
        <primitive object={nodes.Bone037} />
        <primitive object={nodes.Bone014} />
        <primitive object={nodes.Bone035} />
        <primitive object={nodes.Bone036} />
        <primitive object={nodes.Bone038} />
        <skinnedMesh
          geometry={nodes.Cube001.geometry}
          material={materials["Material.026"]}
          skeleton={nodes.Cube001.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.027"]}
          skeleton={nodes.Cube001_1.skeleton}
        />
      </group>
      <group position={[0, 0.554, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_1.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_2.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_3.geometry}
          material={materials["Material.032"]}
        />
      </group>
      <group position={[3.681, 12.348, -10.473]} rotation={[0.769, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={materials.StoneDark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_1.geometry}
          material={materials["White.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_2.geometry}
          material={materials["Metal.076"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant002.geometry}
        material={materials["Material.018"]}
        position={[-2.46, 12.428, -12.829]}
        scale={0.443}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002.geometry}
          material={materials["Material.025"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath001.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath002.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath003.geometry}
          material={materials["Material.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath004.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath005.geometry}
          material={materials["Material.023"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath012.geometry}
          material={materials["Material.024"]}
        />
      </mesh>
      <group
        position={[3.867, 9.683, -10.245]}
        rotation={[-Math.PI, 1.299, -Math.PI]}
        scale={0.226}
      >
        <group position={[0, 0.2, -0.1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_body001.geometry}
            material={materials["plastic.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_body001_1.geometry}
            material={materials["paintBlue.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_body001_2.geometry}
            material={materials["lightFront.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_body001_3.geometry}
            material={materials["_defaultMat.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_body001_4.geometry}
            material={materials["lightBack.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_body001_5.geometry}
            material={materials["window.001"]}
          />
        </group>
        <group
          position={[-0.35, 0.3, 0.76]}
          rotation={[-Math.PI, 0, 0]}
          scale={-1}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft001.geometry}
            material={materials["carTire.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft001_1.geometry}
            material={materials["_defaultMat.001"]}
          />
        </group>
        <group position={[0.35, 0.3, 0.76]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft001.geometry}
            material={materials["carTire.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft001_1.geometry}
            material={materials["_defaultMat.001"]}
          />
        </group>
        <group
          position={[-0.35, 0.3, -0.76]}
          rotation={[-Math.PI, 0, 0]}
          scale={-1}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft001.geometry}
            material={materials["carTire.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft001_1.geometry}
            material={materials["_defaultMat.001"]}
          />
        </group>
        <group position={[0.35, 0.3, -0.76]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft001.geometry}
            material={materials["carTire.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_wheel_frontLeft001_1.geometry}
            material={materials["_defaultMat.001"]}
          />
        </group>
      </group>
      <group
        position={[4.327, 12.228, -9.941]}
        rotation={[3.063, -0.128, 3.132]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials["StoneDark.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials["White.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_2.geometry}
          material={materials["Metal.001"]}
        />
      </group>
      <group position={[3.833, 12.228, -9.12]} rotation={[2.993, -1.02, 3.014]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials["StoneDark.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials["White.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_2.geometry}
          material={materials["Metal.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('models/escenariov2/encenario2.glb')
