/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: Brynn (https://sketchfab.com/Brynnnnn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-isometric-rooms-d53af0ad289a403598ee2cb41d84608b
Title: Low Poly Isometric Rooms
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene(props) {
  const { nodes, materials } = useGLTF('models/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.15, 0.01, 0.15]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.011}>
            <group position={[0, 275, 365]}>
              <group rotation={[0, Math.PI / 2, 0]}>
                <mesh geometry={nodes.Wood_Plank1_Colors_0.geometry} material={materials.Colors} position={[0, 2.5, 100]} />
                <mesh geometry={nodes.Wood_Plank2_Colors_0.geometry} material={materials.Colors} position={[0, 2.5, 50]} />
                <mesh geometry={nodes.Wood_Plank3_Colors_0.geometry} material={materials.Colors} position={[0, 2.5, 0]} />
                <mesh geometry={nodes.Wood_Plank4_Colors_0.geometry} material={materials.Colors} position={[0, 2.5, -50]} />
                <mesh geometry={nodes.Wood_Plank5_Colors_0.geometry} material={materials.Colors} position={[0, 2.5, -100]} />
                <mesh geometry={nodes.Wood_Plank6_Colors_0.geometry} material={materials.Colors} position={[0, 2.5, -150]} />
                <mesh geometry={nodes.Wood_Plank7_Colors_0.geometry} material={materials.Colors} position={[0, 2.5, 150]} />
              </group>
              <group position={[-21.79, 0, 16.03]} rotation={[0, -0.27, 0]}>
                <mesh geometry={nodes.Leg14_Colors_0.geometry} material={materials.Colors} position={[350, -269.5, -65.17]} />
                <mesh geometry={nodes.Leg15_Colors_0.geometry} material={materials.Colors} position={[350, -269.5, -65.17]} />
                <mesh geometry={nodes.Top2_Colors_0.geometry} material={materials.Colors} position={[52.27, -17.5, -16.01]} scale={[0.6, 1, 0.35]} />
              </group>
              <mesh geometry={nodes.Walls2_Colors_0.geometry} material={materials.Colors} />
              <mesh geometry={nodes.Telescope_Colors_0.geometry} material={materials.Colors} position={[-5.01, 5, 162.68]} />
              <mesh geometry={nodes.Bed_Colors_0.geometry} material={materials.Colors} position={[65, 5, 99.73]} rotation={[-Math.PI, 0, -Math.PI]} />
              <mesh geometry={nodes.Shelf1_Colors_0.geometry} material={materials.Colors} position={[-155, 200, -44.13]} />
              <mesh geometry={nodes.Shelf2_Colors_0.geometry} material={materials.Colors} position={[-155, 155, 50]} />
              <mesh geometry={nodes.Book5_Colors_0.geometry} material={materials.Colors} position={[-154.5, 174.81, 30.12]} rotation={[-Math.PI / 10, 0, 0]} />
              <mesh geometry={nodes.Book4_Colors_0.geometry} material={materials.Colors} position={[-154.98, 164, 88.81]} rotation={[-Math.PI / 2, 0, 0.18]} />
              <mesh geometry={nodes.Book3_Colors_0.geometry} material={materials.Colors} position={[-152.26, 174, 118.49]} />
              <mesh geometry={nodes.Book2_Colors_0_1.geometry} material={materials.Colors} position={[-152.26, 174, 15.66]} />
              <mesh geometry={nodes.Book1_Colors_0_1.geometry} material={materials.Colors} position={[-152.26, 174, -9.51]} />
              <mesh geometry={nodes.Book_Colors_0.geometry} material={materials.Colors} position={[-152.26, 174, -21.22]} />
              <mesh geometry={nodes.Book6_Colors_0.geometry} material={materials.Colors} position={[-152.26, 219, -74.43]} />
              <mesh geometry={nodes.Book7_Colors_0.geometry} material={materials.Colors} position={[-152.26, 219, 28.39]} />
              <mesh geometry={nodes.Book8_Colors_0.geometry} material={materials.Colors} position={[-152.26, 219, 17.27]} />
              <mesh geometry={nodes.Book9_Colors_0.geometry} material={materials.Colors} position={[-150.77, 209.02, -14.95]} rotation={[-1.57, -0.01, 0.18]} />
              <mesh geometry={nodes.Book10_Colors_0.geometry} material={materials.Colors} position={[-154.5, 219, -59.97]} rotation={[-Math.PI / 10, 0, 0]} />
              <mesh geometry={nodes.Book11_Colors_0.geometry} material={materials.Colors} position={[-150.77, 218.99, -14.95]} rotation={[-1.57, -0.01, -0.09]} />
              <mesh geometry={nodes.Book12_Colors_0.geometry} material={materials.Colors} position={[-104.35, 76, -133.3]} rotation={[-Math.PI / 2, 0, -0.37]} />
              <mesh geometry={nodes.Book13_Colors_0.geometry} material={materials.Colors} position={[-104.35, 86, -133.3]} rotation={[-Math.PI / 2, 0, -0.03]} />
              <mesh geometry={nodes.Top_Colors_0.geometry} material={materials.Colors} />
              <mesh geometry={nodes.Drawer_Colors_0.geometry} material={materials.Colors} />
              <mesh geometry={nodes.Handle_Colors_0_1.geometry} material={materials.Colors} />
              <mesh geometry={nodes.Leg1_Colors_0.geometry} material={materials.Colors} />
              <mesh geometry={nodes.Leg2_Colors_0.geometry} material={materials.Colors} />
              <mesh geometry={nodes.Leg3_Colors_0.geometry} material={materials.Colors} />
              <mesh geometry={nodes.Computer_Colors_0.geometry} material={materials.Colors} position={[-93.6, 20.15, -38.58]} rotation={[-Math.PI, 1.48, -Math.PI]} scale={0.5} />
              <mesh geometry={nodes.Keyboard_Colors_0.geometry} material={materials.Colors} position={[-100.33, 91, -37.96]} rotation={[0, Math.PI / 2, 0]} scale={[0.5, 0.4, 0.2]} />
              <mesh geometry={nodes.CPU_Colors_0.geometry} material={materials.Colors} position={[-145.33, 91, -103.56]} scale={[0.5, 0.4, 0.2]} />
              <mesh geometry={nodes.Mouse_Colors_0.geometry} material={materials.Colors} position={[-96.75, 91, -82.79]} rotation={[0, Math.PI / 2, 0]} scale={[0.1, 0.4, 0.15]} />
              <mesh geometry={nodes.Top_Colors_0_1.geometry} material={materials.Colors} position={[50, 210, 160]} />
              <mesh geometry={nodes.String1_Colors_0.geometry} material={materials.Colors} position={[-20, 153.47, 157.5]} />
              <mesh geometry={nodes.String2_Colors_0.geometry} material={materials.Colors} position={[120, 153.47, 157.5]} />
              <mesh geometry={nodes.Blind1_Colors_0.geometry} material={materials.Colors} position={[50, 180, 157.5]} rotation={[-Math.PI / 3, 0, 0]} />
              <mesh geometry={nodes.Blind2_Colors_0.geometry} material={materials.Colors} position={[50, 170, 157.5]} rotation={[-Math.PI / 3, 0, 0]} />
              <mesh geometry={nodes.Blind3_Colors_0.geometry} material={materials.Colors} position={[50, 160, 157.5]} rotation={[-Math.PI / 3, 0, 0]} />
              <mesh geometry={nodes.Blind4_Colors_0.geometry} material={materials.Colors} position={[50, 150, 157.5]} rotation={[-Math.PI / 3, 0, 0]} />
              <mesh geometry={nodes.Blind5_Colors_0.geometry} material={materials.Colors} position={[50, 140, 157.5]} rotation={[-Math.PI / 3, 0, 0]} />
              <mesh geometry={nodes.Blind6_Colors_0.geometry} material={materials.Colors} position={[50, 130, 157.5]} rotation={[-Math.PI / 3, 0, 0]} />
              <mesh geometry={nodes.Blind7_Colors_0.geometry} material={materials.Colors} position={[50, 120, 157.5]} rotation={[-Math.PI / 3, 0, 0]} />
              <mesh geometry={nodes.Blind8_Colors_0.geometry} material={materials.Colors} position={[50, 110, 157.5]} rotation={[-Math.PI / 3, 0, 0]} />
              <mesh geometry={nodes.Blind9_Colors_0.geometry} material={materials.Colors} position={[50, 190, 157.5]} rotation={[-Math.PI / 3, 0, 0]} />
            </group>
            <group position={[-365, 275, 0]}>
              <group position={[25, 0, 30]}>
                <mesh geometry={nodes.Top1_Colors_0.geometry} material={materials.Colors} position={[-4, -25, -34.81]} rotation={[0, Math.PI / 2, 0]} scale={[0.5, 1, 0.3]} />
                <mesh geometry={nodes.Leg13_Colors_0.geometry} material={materials.Colors} position={[340, -275, 0]} />
                <mesh geometry={nodes.Leg12_Colors_0.geometry} material={materials.Colors} position={[340, -275, 0]} />
              </group>
              <group position={[0, 0.04, -67.79]} scale={[1, 1.2, 0.5]}>
                <group position={[0, -0.03, 135.57]} scale={[1, 0.83, 2]}>
                  <mesh geometry={nodes.Book1_Colors_0_2.geometry} material={materials.Colors} position={[-150, 212.47, -39.56]} />
                  <mesh geometry={nodes.Book2_Colors_0_2.geometry} material={materials.Colors} position={[-151, 212.47, -49.56]} />
                  <mesh geometry={nodes.Book3_Colors_0_1.geometry} material={materials.Colors} position={[-150, 212.47, -59.56]} />
                  <mesh geometry={nodes.Book4_Colors_0_1.geometry} material={materials.Colors} position={[-151, 212.47, -69.56]} />
                  <mesh geometry={nodes.Book14_Colors_0.geometry} material={materials.Colors} position={[-150, 172.5, -63.36]} />
                  <mesh geometry={nodes.Book15_Colors_0.geometry} material={materials.Colors} position={[-151, 172.5, -73.36]} />
                  <mesh geometry={nodes.Book16_Colors_0.geometry} material={materials.Colors} position={[-150, 172.5, -83.36]} />
                  <mesh geometry={nodes.Book17_Colors_0.geometry} material={materials.Colors} position={[-151, 172.5, -93.36]} />
                  <mesh geometry={nodes.Book18_Colors_0.geometry} material={materials.Colors} position={[-150, 172.5, -103.6]} />
                  <mesh geometry={nodes.Book19_Colors_0.geometry} material={materials.Colors} position={[-151, 172.5, -113.6]} />
                  <mesh geometry={nodes.Book20_Colors_0.geometry} material={materials.Colors} position={[-150, 172.5, -123.6]} />
                  <mesh geometry={nodes.Book21_Colors_0.geometry} material={materials.Colors} position={[-151, 172.5, -133.6]} />
                  <mesh geometry={nodes.Book22_Colors_0.geometry} material={materials.Colors} position={[-151, 137.81, -112.05]} rotation={[0.3, 0, 0]} />
                  <mesh geometry={nodes.Book23_Colors_0.geometry} material={materials.Colors} position={[-150, 137, -97.85]} />
                  <mesh geometry={nodes.Book24_Colors_0.geometry} material={materials.Colors} position={[-151, 137, -87.85]} />
                  <mesh geometry={nodes.Book25_Colors_0.geometry} material={materials.Colors} position={[-150, 137, -77.85]} />
                  <mesh geometry={nodes.Book26_Colors_0.geometry} material={materials.Colors} position={[-151, 137, -67.61]} />
                  <mesh geometry={nodes.Book27_Colors_0.geometry} material={materials.Colors} position={[-150, 137, -57.61]} />
                  <mesh geometry={nodes.Book28_Colors_0.geometry} material={materials.Colors} position={[-151, 137, -47.61]} />
                  <mesh geometry={nodes.Book29_Colors_0.geometry} material={materials.Colors} position={[-150, 137, -37.61]} />
                  <mesh geometry={nodes.Book30_Colors_0.geometry} material={materials.Colors} position={[-150, 97, -103.6]} />
                  <mesh geometry={nodes.Book31_Colors_0.geometry} material={materials.Colors} position={[-151, 97, -113.6]} />
                  <mesh geometry={nodes.Book32_Colors_0.geometry} material={materials.Colors} position={[-150, 97, -123.6]} />
                  <mesh geometry={nodes.Book33_Colors_0.geometry} material={materials.Colors} position={[-151, 97, -133.6]} />
                  <mesh geometry={nodes.Book34_Colors_0.geometry} material={materials.Colors} position={[-153.2, 87, -83.6]} rotation={[Math.PI / 2, 0, 0]} />
                  <mesh geometry={nodes.Book35_Colors_0.geometry} material={materials.Colors} position={[-151.19, 97.48, -83.14]} rotation={[1.58, -0.03, 1.38]} />
                  <mesh geometry={nodes.Book36_Colors_0.geometry} material={materials.Colors} position={[-152.97, 12.06, -77.84]} rotation={[Math.PI / 2, 0, 0.56]} />
                  <mesh geometry={nodes.Book37_Colors_0.geometry} material={materials.Colors} position={[-149.54, 22.06, -80.19]} rotation={[Math.PI / 2, 0, 0.81]} />
                  <mesh geometry={nodes.Book38_Colors_0.geometry} material={materials.Colors} position={[68.66, 86.02, 137.82]} rotation={[Math.PI / 2, 0, 0]} />
                  <mesh geometry={nodes.Book39_Colors_0.geometry} material={materials.Colors} position={[69.29, 76.02, 138.4]} rotation={[Math.PI / 2, 0, -1.66]} />
                </group>
                <mesh geometry={nodes.BookShelf_Colors_0.geometry} material={materials.Colors} />
              </group>
              <group position={[25, 0, 0]}>
                <mesh geometry={nodes.Laptop_Colors_0.geometry} material={materials.Colors} position={[1.82, 4.99, 73.82]} rotation={[-Math.PI, 1.4, -Math.PI]} scale={[0.31, 1, 0.27]} />
                <mesh geometry={nodes.Paper_Colors_0.geometry} material={materials.Colors} position={[-45.94, 54.5, 142.03]} rotation={[0, -0.34, 0]} scale={[0.3, 0.25, 0.25]} />
                <mesh geometry={nodes.Top_Colors_0_2.geometry} material={materials.Colors} position={[45, 0, 0]} rotation={[0, Math.PI / 2, 0]} />
                <mesh geometry={nodes.Leg1_Colors_0_3.geometry} material={materials.Colors} position={[74.99, -10.53, 156.25]} rotation={[Math.PI / 2, -0.26, Math.PI / 2]} scale={[0.05, 1, 0.39]} />
                <mesh geometry={nodes.Leg2_Colors_0_3.geometry} material={materials.Colors} position={[-20.93, -10.53, 143.75]} rotation={[Math.PI / 2, 0.26, -Math.PI / 2]} scale={[0.05, 1, 0.39]} />
                <mesh geometry={nodes.Leg3_Colors_0_3.geometry} material={materials.Colors} position={[-20.93, -10.53, 93.75]} rotation={[Math.PI / 2, 0.26, -Math.PI / 2]} scale={[0.05, 1, 0.39]} />
                <mesh geometry={nodes.Leg4_Colors_0_2.geometry} material={materials.Colors} position={[74.99, -10.53, 106.25]} rotation={[Math.PI / 2, -0.26, Math.PI / 2]} scale={[0.05, 1, 0.39]} />
                <mesh geometry={nodes.Leg8_Colors_0.geometry} material={materials.Colors} position={[-25.05, -10.53, 156.25]} rotation={[Math.PI / 2, -0.26, Math.PI / 2]} scale={[0.05, 1, 0.39]} />
                <mesh geometry={nodes.Leg9_Colors_0.geometry} material={materials.Colors} position={[-120.97, -10.53, 143.75]} rotation={[Math.PI / 2, 0.26, -Math.PI / 2]} scale={[0.05, 1, 0.39]} />
                <mesh geometry={nodes.Leg10_Colors_0.geometry} material={materials.Colors} position={[-120.97, -10.53, 93.75]} rotation={[Math.PI / 2, 0.26, -Math.PI / 2]} scale={[0.05, 1, 0.39]} />
                <mesh geometry={nodes.Leg11_Colors_0.geometry} material={materials.Colors} position={[-25.05, -10.53, 106.25]} rotation={[Math.PI / 2, -0.26, Math.PI / 2]} scale={[0.05, 1, 0.39]} />
                <mesh geometry={nodes.Box_Colors_0.geometry} material={materials.Colors} position={[-149.37, 25.5, -51.46]} rotation={[0, 0.2, 0]} scale={[0.2, 0.25, 0.17]} />
                <mesh geometry={nodes.Box1_Colors_0.geometry} material={materials.Colors} position={[-154.81, 25.5, -90.5]} rotation={[0, -0.23, 0]} scale={[0.2, 0.25, 0.17]} />
                <mesh geometry={nodes.Box2_Colors_0.geometry} material={materials.Colors} position={[-153.96, -9.5, -101.62]} rotation={[0, -0.19, 0]} scale={[0.2, 0.25, 0.17]} />
                <mesh geometry={nodes.Box3_Colors_0.geometry} material={materials.Colors} position={[-162.45, -9.5, -69.46]} rotation={[0, Math.PI / 2, 0]} scale={[0.2, 0.25, 0.17]} />
                <mesh geometry={nodes.Paper7_Colors_0.geometry} material={materials.Colors} position={[-45.94, -16.5, -31.42]} rotation={[0, -0.34, 0]} scale={[0.3, 0.25, 0.25]} />
                <mesh geometry={nodes.Paper8_Colors_0.geometry} material={materials.Colors} position={[11.73, -16.5, -51.89]} rotation={[0, -1.24, 0]} scale={[0.3, 0.25, 0.25]} />
              </group>
              <group position={[-72.5, 200, 165.4]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1.2, 0.5]}>
                <mesh geometry={nodes.Picture13_Colors_0.geometry} material={materials.Colors} position={[5, 7.22, 0]} />
                <mesh geometry={nodes.Picture12_Colors_0.geometry} material={materials.Colors} position={[-33.3, 6.11, 0]} />
                <mesh geometry={nodes.Picture11_Colors_0.geometry} material={materials.Colors} position={[79.88, 0, 0]} />
                <mesh geometry={nodes.Picture10_Colors_0.geometry} material={materials.Colors} position={[5, 0, 0]} />
                <mesh geometry={nodes.Picture9_Colors_0.geometry} material={materials.Colors} position={[5, 7.22, 0]} />
              </group>
              <group position={[-200, 0, 50]}>
                <mesh geometry={nodes.pCube11_Colors_0.geometry} material={materials.Colors} position={[50, 110.43, -46.78]} scale={1.1} />
                <mesh geometry={nodes.pCube10_Colors_0.geometry} material={materials.Colors} position={[50, 60, -50]} />
                <mesh geometry={nodes.pCube9_Colors_0.geometry} material={materials.Colors} position={[50, 20, -50]} />
                <mesh geometry={nodes.pCube12_Colors_0.geometry} material={materials.Colors} position={[43.67, 62.49, -50]} rotation={[0, 0, 0.63]} scale={0.68} />
                <mesh geometry={nodes.pCube13_Colors_0.geometry} material={materials.Colors} position={[35.57, 82.17, -53.05]} scale={0.52} />
                <mesh geometry={nodes.pCube16_Colors_0.geometry} material={materials.Colors} position={[66.43, 116.86, -58.8]} scale={0.52} />
              </group>
              <group position={[-48.62, 70.96, 175.31]} scale={0.46}>
                <mesh geometry={nodes.pCube11_Colors_0_1.geometry} material={materials.Colors} position={[50, 110.43, -50]} scale={1.1} />
                <mesh geometry={nodes.pCube10_Colors_0_1.geometry} material={materials.Colors} position={[50, 60, -50]} />
                <mesh geometry={nodes.pCube9_Colors_0_1.geometry} material={materials.Colors} position={[50, 20, -50]} />
                <mesh geometry={nodes.pCube12_Colors_0_1.geometry} material={materials.Colors} position={[-24.99, 6.93, -39.89]} rotation={[0, -0.75, 0]} />
                <mesh geometry={nodes.pCube13_Colors_0_1.geometry} material={materials.Colors} position={[45, 89.1, -62.39]} scale={0.52} />
                <mesh geometry={nodes.pCube16_Colors_0_1.geometry} material={materials.Colors} position={[66.43, 116.86, -47.87]} scale={0.52} />
              </group>
              <mesh geometry={nodes.Walls2_Colors_0_1.geometry} material={materials.Colors} position={[365, -275, 0]} />
              <group position={[60, 0, 0]}>
                <mesh geometry={nodes.Cork_Board2_Colors_0.geometry} material={materials.Colors} position={[50, 150, 172.5]} rotation={[0, Math.PI / 2, 0]} scale={[1, 2, 2]} />
                <mesh geometry={nodes.Paper3_Colors_0.geometry} material={materials.Colors} position={[107.34, 172.37, 152]} rotation={[Math.PI / 2, 0, 0]} scale={[0.3, 0.25, 0.14]} />
                <mesh geometry={nodes.Paper4_Colors_0.geometry} material={materials.Colors} position={[103.89, 121.01, 152]} rotation={[Math.PI / 2, 0, 0]} scale={[0.3, 0.25, 0.25]} />
                <mesh geometry={nodes.Paper5_Colors_0.geometry} material={materials.Colors} position={[68.01, 135.56, 152]} rotation={[Math.PI / 2, 0, 0]} scale={[0.3, 0.25, 0.25]} />
              </group>
              <group position={[-60, 0, 0]}>
                <mesh geometry={nodes.Paper6_Colors_0.geometry} material={materials.Colors} position={[6.63, 144.2, 152]} rotation={[Math.PI / 2, 0, 0]} scale={[0.3, 0.25, 0.25]} />
                <mesh geometry={nodes.Paper2_Colors_0.geometry} material={materials.Colors} position={[-32.91, 159.57, 152]} rotation={[Math.PI / 2, 0, 0]} scale={[0.3, 0.25, 0.2]} />
                <mesh geometry={nodes.Paper1_Colors_0.geometry} material={materials.Colors} position={[-30.43, 113.97, 152]} rotation={[Math.PI / 2, 0, 0]} scale={[0.3, 0.25, 0.2]} />
                <mesh geometry={nodes.Cork_Board1_Colors_0.geometry} material={materials.Colors} position={[-50, 150, 172.5]} rotation={[0, Math.PI / 2, 0]} scale={[1, 2, 2]} />
              </group>
              <mesh geometry={nodes.Container1_Colors_0.geometry} material={materials.Colors} position={[123.86, 5.18, 109.97]} rotation={[0.01, -1.11, 0.01]} scale={1.49} />
              <mesh geometry={nodes.Paper_Roll_Colors_0.geometry} material={materials.Colors} position={[-72.39, 10.38, -77.37]} rotation={[Math.PI / 2, 0, 0.63]} />
            </group>
            <group position={[365, 0, 365]}>
              <group position={[365, 0, -355]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes.Cushion_Top1_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Cushion_Top2_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Cushion_Top3_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Cushion_Bottom1_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Cushion_Bottom2_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Cushion_Bottom3_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Cushion_Top4_Colors_0.geometry} material={materials.Colors} position={[63.69, 57.84, 351.35]} rotation={[0.15, 0.65, -0.09]} scale={0.65} />
                <mesh geometry={nodes.Cushion_Top5_Colors_0.geometry} material={materials.Colors} position={[45.55, 57.84, 351.35]} rotation={[0.15, 0.65, -0.09]} scale={0.65} />
                <mesh geometry={nodes.Cushion_Top6_Colors_0.geometry} material={materials.Colors} position={[402.59, 18.84, 139.18]} rotation={[-0.03, -1.03, -0.06]} scale={0.65} />
                <mesh geometry={nodes.Frame_Back_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Frame_Bottom_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Leg1_Colors_0_1.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Leg2_Colors_0_1.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Leg3_Colors_0_1.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Leg4_Colors_0.geometry} material={materials.Colors} />
              </group>
              <group position={[321.49, 0, -384.88]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes.Table_Body_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Handle_Colors_0_2.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Drawer_Colors_0_1.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Leg1_Colors_0_2.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Leg2_Colors_0_2.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Leg3_Colors_0_2.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Leg4_Colors_0_1.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Tissue_Box_Colors_0.geometry} material={materials.Colors} />
              </group>
              <group position={[83.44, 0, -26.56]} rotation={[0, -Math.PI / 2, 0]} scale={0.8}>
                <mesh geometry={nodes.TV_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Dresser_Colors_0.geometry} material={materials.Colors} />
              </group>
              <group position={[100, 0, -75]}>
                <mesh geometry={nodes.pCube11_Colors_0_2.geometry} material={materials.Colors} position={[50, 100, -50]} />
                <mesh geometry={nodes.pCube10_Colors_0_2.geometry} material={materials.Colors} position={[50, 60, -50]} />
                <mesh geometry={nodes.pCube9_Colors_0_2.geometry} material={materials.Colors} position={[50, 20, -50]} />
              </group>
              <mesh geometry={nodes.Walls_Colors_0.geometry} material={materials.Colors} />
              <mesh geometry={nodes.Picture_Colors_0_1.geometry} material={materials.Colors} position={[10, 170, 172.5]} rotation={[0, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Picture1_Colors_0.geometry} material={materials.Colors} position={[-96, 175, 172.5]} rotation={[0, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Picture2_Colors_0.geometry} material={materials.Colors} position={[-40.99, 175, 172.5]} rotation={[0, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Picture3_Colors_0.geometry} material={materials.Colors} position={[-90, 120, 172.5]} rotation={[0, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Picture4_Colors_0.geometry} material={materials.Colors} position={[-30, 120, 172.5]} rotation={[0, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Picture6_Colors_0.geometry} material={materials.Colors} position={[-172.5, 175, -120]} scale={[1, 1.5, 1.5]} />
              <mesh geometry={nodes.Picture7_Colors_0.geometry} material={materials.Colors} position={[-172.5, 175, 70]} scale={[1, 1.5, 1.5]} />
              <mesh geometry={nodes.Picture8_Colors_0.geometry} material={materials.Colors} position={[-172.5, 175, -25]} scale={[1, 2, 2]} />
            </group>
            <group position={[-365, 0, -365]}>
              <group position={[-59.88, 0, 43.69]}>
                <mesh geometry={nodes.polySurface1_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.polySurface2_Colors_0.geometry} material={materials.Colors} />
              </group>
              <group position={[65, 0, 40]} rotation={[-Math.PI, 0, -Math.PI]}>
                <group scale={[1, 1, 1.5]}>
                  <group scale={[1, 1, 0.67]}>
                    <mesh geometry={nodes.polySurface10_Colors_0.geometry} material={materials.Colors} position={[0, 0, 22.5]} />
                    <mesh geometry={nodes.polySurface11_Colors_0.geometry} material={materials.Colors} position={[0, 0, -26.5]} />
                  </group>
                  <mesh geometry={nodes.polySurface4_Colors_0.geometry} material={materials.Colors} />
                  <mesh geometry={nodes.polySurface7_Colors_0.geometry} material={materials.Colors} position={[9.6, 0, 0]} />
                </group>
                <mesh geometry={nodes.Matress_Colors_0.geometry} material={materials.Colors} scale={[1, 1, 1.5]} />
                <mesh geometry={nodes.Pillow1_Colors_0.geometry} material={materials.Colors} position={[7.22, -23.83, -42.5]} rotation={[0, 0, 0.12]} />
                <mesh geometry={nodes.Pillow2_Colors_0.geometry} material={materials.Colors} position={[7.22, -23.83, 42.5]} rotation={[0, 0, 0.12]} />
              </group>
              <mesh geometry={nodes.Walls_Colors_0_2.geometry} material={materials.Colors} />
              <mesh geometry={nodes.Curtain_Holder_Colors_0.geometry} material={materials.Colors} position={[0, 200, 165]} />
              <mesh geometry={nodes.Blind1_Colors_0_1.geometry} material={materials.Colors} position={[90, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind2_Colors_0_1.geometry} material={materials.Colors} position={[80, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind3_Colors_0_1.geometry} material={materials.Colors} position={[70, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind4_Colors_0_1.geometry} material={materials.Colors} position={[60, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind5_Colors_0_1.geometry} material={materials.Colors} position={[50, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind6_Colors_0_1.geometry} material={materials.Colors} position={[40, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind7_Colors_0_1.geometry} material={materials.Colors} position={[30, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind8_Colors_0_1.geometry} material={materials.Colors} position={[20, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind9_Colors_0_1.geometry} material={materials.Colors} position={[10, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind10_Colors_0.geometry} material={materials.Colors} position={[0, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind11_Colors_0.geometry} material={materials.Colors} position={[-10, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind12_Colors_0.geometry} material={materials.Colors} position={[-20, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind13_Colors_0.geometry} material={materials.Colors} position={[-30, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind14_Colors_0.geometry} material={materials.Colors} position={[-40, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind15_Colors_0.geometry} material={materials.Colors} position={[-50, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind16_Colors_0.geometry} material={materials.Colors} position={[-60, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind17_Colors_0.geometry} material={materials.Colors} position={[-70, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Blind18_Colors_0.geometry} material={materials.Colors} position={[-80, 100, 165]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Airconditioner_Colors_0.geometry} material={materials.Colors} position={[-160, 220, 60]} />
              <mesh geometry={nodes.Picture1_Colors_0_1.geometry} material={materials.Colors} position={[-172.46, 140, 100]} scale={[1, 2, 2]} />
              <mesh geometry={nodes.Picture2_Colors_0_1.geometry} material={materials.Colors} position={[-172.46, 140, 0]} scale={[1, 2, 2]} />
              <mesh geometry={nodes.Picture3_Colors_0_1.geometry} material={materials.Colors} position={[-172.46, 140, -100]} scale={[1, 2, 2]} />
              <mesh geometry={nodes.pCube17_Colors_0.geometry} material={materials.Colors} position={[-150, 30, -100]} />
              <mesh geometry={nodes.pCube18_Colors_0.geometry} material={materials.Colors} position={[-127.3, 45.96, -100]} />
              <mesh geometry={nodes.pCube19_Colors_0.geometry} material={materials.Colors} position={[-127.3, 19.16, -100]} />
              <mesh geometry={nodes.pCube20_Colors_0.geometry} material={materials.Colors} position={[-120.93, 49.33, -100]} />
              <mesh geometry={nodes.pCube21_Colors_0.geometry} material={materials.Colors} position={[-120.93, 23.04, -100]} />
              <mesh geometry={nodes.Book41_Colors_0.geometry} material={materials.Colors} position={[-152.08, 65.01, -111.68]} rotation={[Math.PI / 2, 0, -1.66]} />
              <mesh geometry={nodes.Book40_Colors_0.geometry} material={materials.Colors} position={[-152.71, 75.01, -112.27]} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.Carpet2_Colors_0.geometry} material={materials.Colors} position={[80, 1.5, 50]} rotation={[0, Math.PI / 2, 0]} scale={[1.35, 0.03, 0.9]} />
            </group>
            <group position={[365, -275, 0]}>
              <group position={[-167, 0, -7.5]} scale={[20, 20, 25]}>
                <mesh geometry={nodes.tap_low_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.stopper_low_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.soap_low_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.sink_low_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Sink_Shelf_Colors_0.geometry} material={materials.Colors} position={[-9.9, 13.75, 0.3]} scale={[0.05, 0.05, 0.04]} />
                <mesh geometry={nodes.Mirror_Colors_0.geometry} material={materials.Colors} position={[-0.28, 8.75, -4.1]} scale={[0.05, 0.1, 0.08]} />
              </group>
              <group position={[-158.5, 0, -10]} scale={20}>
                <mesh geometry={nodes.tank_low_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.flush_low_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.lid_low_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.bowl_low_Colors_0.geometry} material={materials.Colors} />
              </group>
              <group position={[0, 0, -25]}>
                <mesh geometry={nodes.pCube5_Colors_0.geometry} material={materials.Colors} position={[115, 75, 173.5]} rotation={[0, 0, Math.PI / 2]} scale={[1, 0.9, 0.75]} />
                <mesh geometry={nodes.pCube4_Colors_0.geometry} material={materials.Colors} position={[115, 160, 184.5]} rotation={[0, 0, Math.PI / 2]} scale={[1, 0.9, 0.75]} />
                <mesh geometry={nodes.pCube3_Colors_0.geometry} material={materials.Colors} position={[115, 120, 180]} rotation={[0, 0, Math.PI / 2]} scale={[1, 0.9, 0.75]} />
                <mesh geometry={nodes.pCube2_Colors_0.geometry} material={materials.Colors} position={[70, 100.47, 177.26]} rotation={[0.12, 0, 0]} scale={[1, 2, 1]} />
                <mesh geometry={nodes.pCube1_Colors_0.geometry} material={materials.Colors} position={[160, 100.47, 177.26]} rotation={[0.12, 0, 0]} scale={[1, 2, 1]} />
              </group>
              <group position={[99.1, 125, 154.44]} rotation={[0, -0.15, 0]}>
                <mesh geometry={nodes.Tray_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.soap_low2_Colors_0.geometry} material={materials.Colors} position={[-49.3, -141.14, 108.37]} rotation={[0, -0.43, 0]} scale={[31.37, 29.61, 34.94]} />
                <mesh geometry={nodes.soap_low1_Colors_0.geometry} material={materials.Colors} position={[31.7, -141.14, 121.11]} rotation={[0, 0.15, 0]} scale={[29.61, 29.61, 37.01]} />
              </group>
              <group position={[100, 0, -50]}>
                <mesh geometry={nodes.pCube11_Colors_0_3.geometry} material={materials.Colors} position={[50, 100, -50]} />
                <mesh geometry={nodes.pCube10_Colors_0_3.geometry} material={materials.Colors} position={[50, 60, -50]} />
                <mesh geometry={nodes.pCube9_Colors_0_3.geometry} material={materials.Colors} position={[50, 20, -50]} />
                <mesh geometry={nodes.pCube14_Colors_0.geometry} material={materials.Colors} position={[35.57, 92.43, -36.61]} scale={0.52} />
                <mesh geometry={nodes.pCube15_Colors_0.geometry} material={materials.Colors} position={[62.35, 105.69, -61.97]} scale={0.52} />
              </group>
              <group position={[100, 0, -100]}>
                <mesh geometry={nodes.pCube11_Colors_0_4.geometry} material={materials.Colors} position={[50, 110.43, -50]} scale={1.1} />
                <mesh geometry={nodes.pCube10_Colors_0_4.geometry} material={materials.Colors} position={[50, 60, -50]} />
                <mesh geometry={nodes.pCube9_Colors_0_4.geometry} material={materials.Colors} position={[50, 20, -50]} />
                <mesh geometry={nodes.pCube12_Colors_0_2.geometry} material={materials.Colors} position={[43.67, 62.49, -50]} rotation={[0, 0, 0.63]} scale={0.68} />
                <mesh geometry={nodes.pCube13_Colors_0_2.geometry} material={materials.Colors} position={[35.57, 82.17, -53.05]} scale={0.52} />
                <mesh geometry={nodes.pCube16_Colors_0_2.geometry} material={materials.Colors} position={[66.43, 116.86, -47.87]} scale={0.52} />
              </group>
              <mesh geometry={nodes.Tissue_Box1_Colors_0.geometry} material={materials.Colors} position={[-289.41, 73.5, 194.2]} rotation={[0, 0.9, 0]} />
              <mesh geometry={nodes.Walls_Colors_0_3.geometry} material={materials.Colors} />
              <mesh geometry={nodes.Rod_Colors_0.geometry} material={materials.Colors} position={[-62.5, 225, 50]} />
              <mesh geometry={nodes.Curtain_Colors_0.geometry} material={materials.Colors} position={[-90, 115, 46.5]} />
              <mesh geometry={nodes.Tub_Colors_0.geometry} material={materials.Colors} position={[-62.5, 35, 112.5]} />
              <mesh geometry={nodes.Handle_Colors_0.geometry} material={materials.Colors} position={[-65, 112.5, 165]} scale={[0.68, 1, 1]} />
              <mesh geometry={nodes.Showhead_Colors_0.geometry} material={materials.Colors} position={[-105.61, 0.91, 282.31]} scale={[40.92, 40.92, 51.15]} />
              <mesh geometry={nodes.Showerpipe_Colors_0.geometry} material={materials.Colors} position={[-162, 220, 112.5]} rotation={[Math.PI / 2, 0, 0]} scale={[0.68, 1, 1]} />
              <mesh geometry={nodes.Showerpipe1_Colors_0.geometry} material={materials.Colors} position={[-162, 87.04, 112.5]} rotation={[Math.PI / 2, 0, 0]} scale={[0.68, 1, 1]} />
              <mesh geometry={nodes.stopper_low1_Colors_0.geometry} material={materials.Colors} position={[-75, -75, 218]} scale={[20, 20, 25]} />
              <mesh geometry={nodes.Carpet_Colors_0_1.geometry} material={materials.Colors} position={[-35, 1, -2.5]} scale={[1.35, 0.03, 0.9]} />
              <mesh geometry={nodes.Bottle1_Colors_0.geometry} material={materials.Colors} position={[105.83, 168.78, 160.99]} rotation={[0, 0.26, 0]} scale={0.13} />
              <mesh geometry={nodes.Bottle2_Colors_0.geometry} material={materials.Colors} position={[121.33, 168.78, 158.52]} rotation={[0, -0.11, 0]} scale={0.13} />
              <mesh geometry={nodes.Bottle3_Colors_0.geometry} material={materials.Colors} position={[144.76, 83.78, 149.36]} rotation={[0, 0.17, 0]} scale={0.13} />
              <mesh geometry={nodes.Bottle4_Colors_0.geometry} material={materials.Colors} position={[83.29, 83.78, 147.84]} rotation={[0, -0.01, 0]} scale={0.13} />
              <mesh geometry={nodes.Bottle5_Colors_0.geometry} material={materials.Colors} position={[127.84, 85, 149.22]} rotation={[0, -0.01, 0]} scale={0.15} />
              <mesh geometry={nodes.Bottle6_Colors_0.geometry} material={materials.Colors} position={[86.2, 170, 158.75]} rotation={[0, -Math.PI / 9, 0]} scale={0.15} />
              <mesh geometry={nodes.Container_Colors_0.geometry} material={materials.Colors} position={[-154.04, 34.98, -127.58]} rotation={[0.01, -1.11, 0.01]} />
              <mesh geometry={nodes.Toilet_Paper_Colors_0.geometry} material={materials.Colors} position={[-149.97, 39, -73.2]} />
              <mesh geometry={nodes.Toilet_Paper1_Colors_0.geometry} material={materials.Colors} position={[-163.19, 39, -90.36]} rotation={[0, -0.57, 0]} />
              <mesh geometry={nodes.Toilet_Paper2_Colors_0.geometry} material={materials.Colors} position={[-158.87, 51.49, -82.51]} rotation={[0, 0.45, 0]} />
              <mesh geometry={nodes.Picture_Colors_0_2.geometry} material={materials.Colors} position={[-172.5, 193.02, 4.84]} scale={[1, 0.99, 0.99]} />
              <mesh geometry={nodes.Picture14_Colors_0.geometry} material={materials.Colors} position={[-172.5, 175.88, -38.81]} />
              <mesh geometry={nodes.Picture15_Colors_0.geometry} material={materials.Colors} position={[-172.5, 144.68, -0.62]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.67, 0.67]} />
              <mesh geometry={nodes.Carpet1_Colors_0.geometry} material={materials.Colors} position={[117.21, 32.77, 128.09]} scale={[0.56, 0.06, 0.37]} />
            </group>
            <group position={[0, -275, -365]}>
              <group position={[-29.19, 0, 65.77]}>
                <mesh geometry={nodes.Side_Left_Colors_0.geometry} material={materials.Colors} position={[-125, 50, 100]} />
                <mesh geometry={nodes.Side_Right_Colors_0.geometry} material={materials.Colors} position={[-125, 50, -50]} />
                <mesh geometry={nodes.Shelf_Bottom_Colors_0.geometry} material={materials.Colors} position={[-127.5, 35, 25]} rotation={[0, 0, -0.26]} />
                <mesh geometry={nodes.Shelf_Top_Colors_0.geometry} material={materials.Colors} position={[-127.5, 70, 25]} rotation={[0, 0, -0.26]} />
                <mesh geometry={nodes.Dumbell1_Colors_0.geometry} material={materials.Colors} position={[-125.54, 80, 60]} rotation={[0, 0, 1.31]} />
                <mesh geometry={nodes.Dumbell2_Colors_0.geometry} material={materials.Colors} position={[-125.54, 80, 80]} rotation={[0, 0, 1.31]} />
                <mesh geometry={nodes.Dumbell3_Colors_0.geometry} material={materials.Colors} position={[-125.54, 80, 40]} rotation={[0, 0, 1.31]} />
                <mesh geometry={nodes.Dumbell4_Colors_0.geometry} material={materials.Colors} position={[-125.54, 80, 20]} rotation={[0, 0, 1.31]} />
                <mesh geometry={nodes.Dumbell5_Colors_0.geometry} material={materials.Colors} position={[-125.54, 80, 0]} rotation={[0, 0, 1.31]} />
                <mesh geometry={nodes.Dumbell6_Colors_0.geometry} material={materials.Colors} position={[-125.54, 80, -20]} rotation={[0, 0, 1.31]} />
                <mesh geometry={nodes.Dumbell7_Colors_0.geometry} material={materials.Colors} position={[-125.54, 45, 70]} rotation={[0, 0, 1.31]} />
                <mesh geometry={nodes.Dumbell8_Colors_0.geometry} material={materials.Colors} position={[-125.54, 45, 50]} rotation={[0, 0, 1.31]} />
                <mesh geometry={nodes.Dumbell9_Colors_0.geometry} material={materials.Colors} position={[-125.54, 45, 30]} rotation={[0, 0, 1.31]} />
                <mesh geometry={nodes.Dumbell10_Colors_0.geometry} material={materials.Colors} position={[-125.54, 45, 10]} rotation={[0, 0, 1.31]} />
                <mesh geometry={nodes.Dumbell11_Colors_0.geometry} material={materials.Colors} position={[-125.54, 45, -10]} rotation={[0, 0, 1.31]} />
                <mesh geometry={nodes.Dumbell12_Colors_0.geometry} material={materials.Colors} position={[-125.54, 45, -30]} rotation={[0, 0, 1.31]} />
              </group>
              <group position={[30, 0, 20]} scale={0.8}>
                <mesh geometry={nodes.Treadmill_Panel_Colors_0.geometry} material={materials.Colors} position={[75, 125, 135]} rotation={[-Math.PI / 6, 0, 0]} scale={[1, 1, 0.2]} />
                <mesh geometry={nodes.Treadmill_base_Colors_0.geometry} material={materials.Colors} position={[75, 10, 55]} />
              </group>
              <mesh geometry={nodes.Walls1_Colors_0.geometry} material={materials.Colors} />
              <mesh geometry={nodes.TV1_Colors_0.geometry} material={materials.Colors} position={[-130.11, 110.92, 49.6]} rotation={[Math.PI / 2, 1.31, -Math.PI / 2]} scale={0.55} />
              <mesh geometry={nodes.YogaBall_Colors_0.geometry} material={materials.Colors} position={[-84.11, 25, 137.15]} rotation={[-0.48, 0.1, -0.5]} />
              <mesh geometry={nodes.Seat_Colors_0.geometry} material={materials.Colors} position={[-150, 40, -80]} />
              <mesh geometry={nodes.Leg_Colors_0.geometry} material={materials.Colors} position={[-150, 5, -150]} />
              <mesh geometry={nodes.Leg5_Colors_0.geometry} material={materials.Colors} position={[-150, 5, -10]} />
              <mesh geometry={nodes.Leg6_Colors_0.geometry} material={materials.Colors} position={[-150, 21.05, -20.23]} rotation={[-Math.PI / 6, 0, 0]} scale={[0.18, 3.58, 0.67]} />
              <mesh geometry={nodes.Leg7_Colors_0.geometry} material={materials.Colors} position={[-150, 21.05, -139.46]} rotation={[Math.PI / 6, 0, 0]} scale={[0.18, 3.58, 0.67]} />
              <mesh geometry={nodes.Cork_Board_Colors_0.geometry} material={materials.Colors} position={[-175, 150, -80]} scale={[1, 2, 2]} />
              <mesh geometry={nodes.pCube8_Colors_0.geometry} material={materials.Colors} position={[-34.43, 1, -79.69]} rotation={[0, Math.PI / 2, 0]} scale={[1.35, 0.03, 0.9]} />
              <mesh geometry={nodes.YogaBall1_Colors_0.geometry} material={materials.Colors} position={[-29.03, 25, 123.13]} rotation={[-0.76, 0.1, 0.48]} />
              <mesh geometry={nodes.Note1_Colors_0.geometry} material={materials.Colors} position={[-171.51, 145.74, -57.38]} rotation={[0.09, 0, 0]} />
              <mesh geometry={nodes.Note2_Colors_0.geometry} material={materials.Colors} position={[-171.51, 173.04, -102.14]} rotation={[-0.05, 0, 0]} />
              <mesh geometry={nodes.Note3_Colors_0.geometry} material={materials.Colors} position={[-171.51, 172.11, -63.89]} />
              <mesh geometry={nodes.Note4_Colors_0.geometry} material={materials.Colors} position={[-171.51, 126.43, -103.22]} />
              <mesh geometry={nodes.Note5_Colors_0.geometry} material={materials.Colors} position={[-171.51, 169.03, -78.03]} />
              <mesh geometry={nodes.Note6_Colors_0.geometry} material={materials.Colors} position={[-171.51, 132.67, -64.33]} />
            </group>
            <group position={[-10, 0, 0]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes.pCube7_Colors_0.geometry} material={materials.Colors} position={[30, 167.5, 152.5]} />
              <mesh geometry={nodes.Pan_Colors_0.geometry} material={materials.Colors} position={[29.57, 133.75, 148.78]} rotation={[Math.PI / 2, 0, 2.79]} />
              <mesh geometry={nodes.Pan1_Colors_0.geometry} material={materials.Colors} position={[-5.43, 133.75, 148.78]} rotation={[Math.PI / 2, 0, 2.79]} />
              <mesh geometry={nodes.Pan2_Colors_0.geometry} material={materials.Colors} position={[64.57, 133.75, 148.78]} rotation={[Math.PI / 2, 0, 2.79]} />
              <mesh geometry={nodes.Pan3_Colors_0.geometry} material={materials.Colors} position={[130.03, 104.61, -81.17]} rotation={[-Math.PI, 1.07, -Math.PI]} />
            </group>
            <group scale={[1, 0.9, 1]}>
              <group position={[-21.08, -150.08, 353.52]} scale={[100, 111.11, 100]}>
                <mesh geometry={nodes.Cup_Colors_0.geometry} material={materials.Colors} position={[0.08, 0, -0.07]} />
                <mesh geometry={nodes.Cup1_Colors_0.geometry} material={materials.Colors} position={[-2.49, 0, -0.97]} rotation={[0, -1.29, 0]} />
                <mesh geometry={nodes.Cup2_Colors_0.geometry} material={materials.Colors} position={[1.27, 0, -0.8]} rotation={[0, 0.75, 0]} />
              </group>
              <group position={[-322.59, -24.95, 69.18]} rotation={[-Math.PI, -1.28, -Math.PI]} scale={[100, 111.11, 100]}>
                <mesh geometry={nodes.Button_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Button1_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Cap_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Jug_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Base_Colors_0.geometry} material={materials.Colors} />
              </group>
              <mesh geometry={nodes.Stove_Top_Colors_0.geometry} material={materials.Colors} position={[48.2, 106.2, 119.28]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1, 0.85]} />
              <mesh geometry={nodes.Counter_Colors_0.geometry} material={materials.Colors} position={[-125, 50, 125]} />
              <group position={[86.39, 47.5, 73]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1, 0.85]}>
                <mesh geometry={nodes.Door1_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Handle1_Colors_0_1.geometry} material={materials.Colors} position={[5.97, 0, 27.77]} scale={[1, 0.5, 0.07]} />
              </group>
              <group position={[24.39, 47.5, 73]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1, 0.85]}>
                <mesh geometry={nodes.Door2_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Handle2_Colors_0_1.geometry} material={materials.Colors} position={[5.97, 0, 26.07]} scale={[1, 0.5, 0.07]} />
              </group>
              <group position={[-37.61, 47.5, 73]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1, 0.85]}>
                <mesh geometry={nodes.Door3_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Handle3_Colors_0_1.geometry} material={materials.Colors} position={[5.97, 0, 26.56]} scale={[1, 0.5, 0.07]} />
              </group>
              <group position={[-41.33, 47.5, 48.81]} rotation={[0, -1.25, 0]}>
                <mesh geometry={nodes.Door4_Colors_0.geometry} material={materials.Colors} />
                <mesh geometry={nodes.Handle4_Colors_0.geometry} material={materials.Colors} position={[6, 0, -29.5]} scale={[1, 0.5, 0.06]} />
              </group>
              <mesh geometry={nodes.Trash_Colors_0.geometry} material={materials.Colors} position={[-105.95, 36.13, 26.45]} rotation={[0, 0.17, 0]} scale={[0.5, 0.55, 0.5]} />
              <mesh geometry={nodes.Tap_Colors_0.geometry} material={materials.Colors} position={[-145, 121.67, 25]} scale={[1, 1.11, 1]} />
              <mesh geometry={nodes.Hot_Colors_0.geometry} material={materials.Colors} position={[-145, 122.22, 35]} scale={[1, 1.11, 1]} />
              <mesh geometry={nodes.Cold_Colors_0.geometry} material={materials.Colors} position={[-145, 122.22, 15]} scale={[1, 1.11, 1]} />
              <mesh geometry={nodes.Cold1_Colors_0.geometry} material={materials.Colors} position={[-112.5, 99.53, 25]} scale={[1, 1.11, 1]} />
              <mesh geometry={nodes.Stove_Top1_Colors_0.geometry} material={materials.Colors} position={[48.78, 109, 91.5]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1, 0.85]} />
              <mesh geometry={nodes.Stove_Top2_Colors_0.geometry} material={materials.Colors} position={[48.78, 109, 129.82]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1, 0.85]} />
              <mesh geometry={nodes.Thing_above_the_stove_i_dont_really_know_wat_its_called_Colors_0.geometry} material={materials.Colors} position={[503.43, -57.77, 455.69]} scale={[100, 111.11, 100]} />
            </group>
            <group rotation={[-Math.PI, 0, -Math.PI]}>
              <mesh geometry={nodes.Metal_Colors_0.geometry} material={materials.Colors} position={[-150, 40, -152.5]} rotation={[Math.PI, 0, -Math.PI]} />
              <mesh geometry={nodes.Paper_Colors_0_1.geometry} material={materials.Colors} position={[-150, 40, -110]} rotation={[Math.PI, 0, -Math.PI]} />
              <mesh geometry={nodes.Plastic_Colors_0.geometry} material={materials.Colors} position={[-150, 40, -67.5]} rotation={[Math.PI, 0, -Math.PI]} />
            </group>
            <mesh geometry={nodes.Walls_Colors_0_1.geometry} material={materials.Colors} />
            <mesh geometry={nodes.Top_Shelf_Colors_0.geometry} material={materials.Colors} position={[-137.5, 190, 137.5]} />
            <mesh geometry={nodes.Book1_Colors_0.geometry} material={materials.Colors} position={[-117.37, 100, 141.72]} rotation={[-Math.PI / 2, 0, 0.17]} />
            <mesh geometry={nodes.Book2_Colors_0.geometry} material={materials.Colors} position={[-117.37, 110, 145.99]} rotation={[-Math.PI / 2, 0, Math.PI / 6]} />
            <mesh geometry={nodes.Ice_Dispenser_Colors_0.geometry} material={materials.Colors} position={[-109, 144.35, -71]} />
            <mesh geometry={nodes.Handle1_Colors_0.geometry} material={materials.Colors} position={[-102, 137.5, -97.5]} />
            <mesh geometry={nodes.Handle2_Colors_0.geometry} material={materials.Colors} position={[-102, 137.5, -112.5]} />
            <mesh geometry={nodes.Handle3_Colors_0.geometry} material={materials.Colors} position={[-102, 65, -105]} rotation={[Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Fridge_Colors_0.geometry} material={materials.Colors} position={[-145, 100, -105]} />
            <mesh geometry={nodes.Carpet_Colors_0.geometry} material={materials.Colors} position={[28.05, 1, 12.85]} scale={[1.35, 0.03, 0.9]} />
            <mesh geometry={nodes.Picture_Colors_0.geometry} material={materials.Colors} position={[-172.5, 140, 127.5]} scale={[1, 1.5, 1.5]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/scene.gltf')
